USE [master]
GO

/****** Object:  Database [InfPortal]    Script Date: 11/25/2017 16:30:20 ******/
CREATE DATABASE [InfPortal] ON  PRIMARY 
( NAME = N'InfPortal', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\InfPortal.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'InfPortal_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\InfPortal_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [InfPortal] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InfPortal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InfPortal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InfPortal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InfPortal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InfPortal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InfPortal] SET ARITHABORT OFF 
GO

ALTER DATABASE [InfPortal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InfPortal] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [InfPortal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InfPortal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InfPortal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InfPortal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InfPortal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InfPortal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InfPortal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InfPortal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InfPortal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InfPortal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InfPortal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InfPortal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InfPortal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InfPortal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InfPortal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InfPortal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InfPortal] SET  READ_WRITE 
GO

ALTER DATABASE [InfPortal] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [InfPortal] SET  MULTI_USER 
GO

ALTER DATABASE [InfPortal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InfPortal] SET DB_CHAINING OFF 
GO

